---

- name: check to see if cockpit is listening
  become: no
  uri:
    url: "https://{{ inventory_hostname }}:9090/system"
    url_username: "{{ system_user }}"
    url_password: "{{ workshop_password }}"
    validate_certs: no
  delegate_to: localhost
  ignore_errors: true
  register: result

- name: if a node fails, restart the cockpit service
  systemd:
    name: "cockpit.socket"
    state: "started"
    enabled: true
    daemon_reload: true
  when: result.failed

- name: check to see if cockpit is listening (again)
  become: no
  uri:
    url: "https://{{ inventory_hostname }}:9090/system"
    url_username: "{{ system_user }}"
    url_password: "{{ workshop_password }}"
    validate_certs: no
  delegate_to: localhost

...
