galaxy_info:
  author: Alexander Jacocks
  description: vscode role
  issue_tracker_url: https://github.com/RedHatGov/redhatgov.roles/issues
  license: GPL
  min_ansible_version: 2.4
  github_branch: master
  platforms:
  - name: EL
    versions:
    - 7
    - 8

  galaxy_tags:
  - vscode

dependencies: []

